site_name: Ireland Energy Wiki by the Energy Modelling Network Ireland
site_description: 'Actively maintained listings of Irish energy-related resources'
site_url: https://energy-modelling-ireland.github.io/ireland-energy-wiki/
repo_name: 'energy-modelling-ireland/ireland-energy-wiki'
repo_url: 'https://github.com/energy-modelling-ireland/ireland-energy-wiki'
theme:
  name: material
  logo: 'logo.png'
  favicon: 'favicon.png'
  palette:
    primary: 'teal'
    accent: 'light'
